/* eslint-disable @next/next/no-html-link-for-pages */
import Head from "next/head";
export default function Home() {
  setTimeout(function () {
    window.location.href = "/controls";
  }, 50);

  return (
    <>
      <Head>
        <title>Echo - Humanoid</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Please go to <a href="/controls">/controls</a> page</h1>
      </main>
    </>
  );
}
