import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import EyeRight from "@/components/EyeRight";
import EyeBrow from "@/components/EyeBrowLeft";
import EyeLids from "@/components/EyeLids";
import Jaw from "@/components/Jaw";
import Tilt from "@/components/Tilt";
import Twist from "@/components/Twist";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Echo - Humanoid</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <EyeLids>{/* <EyeRight/> */}</EyeLids>
      </main>
    </>
  );
}
